config/routes.rb
ProjectLectito::Application.routes.draw do

  # Devise routes
  authenticated :user do
    root :to => 'inventory#search'
  end

  unauthenticated :user do
    devise_scope :user do 
      get '/' => 'devise/sessions#new'
      get '/users/confirmation/new' => 'devise/passwords#new'
      get '/inventory/search' => 'devise/sessions#new'
    end
  end

  # Chat Routes
  get 'chat/box_chat_history' => 'chat#box_chat_history'
  post 'chat/new_chat' => 'chat#new_chat'

  # Profile Routes
  get 'profile/rating' => 'profile#rating'
  get 'profile/verification' => 'profile#otp'
  get 'profile/otp_resend' => 'profile#otp_resend'
  get 'profile/otp_verified' => 'profile#otp_verified'
  get 'profile/otp_verification' => 'profile#otp_verification'
  get 'profile/public_rating/:tr_id' => 'profile#public_rating'
  get 'profile/user_barred_signout' => 'profile#user_barred_signout'
  #FIXME - Patch gives FF Popup error
  post 'profile/online' => 'profile#online'

  # Address Routes
  get 'address/autocomplete_area' => 'address#autocomplete_area'
  get 'address/:id/autocomplete_area' => 'address#autocomplete_area'

  # Admin routes
  get 'admin' => 'admin#index', as: 'admin_index'
  get 'admin/user_details' => 'admin#user_details'
  get 'admin/user_transaction_history/:id' => 'admin#user_transaction_history', as: 'user_transaction_history'
  patch 'admin/bar_user' => 'admin#bar_user'
  patch 'admin/unbar_user' => 'admin#unbar_user'

  get 'devise/User'

  # Book Routes
  get 'book/history/:id' => 'book#history', as: 'book_history'
  get 'book/book_status' => 'book#book_status'
  get 'book/available_book_stats' => 'book#available_book_stats'
  get 'book/borrowed_book_stats' => 'book#borrowed_book_stats'

  # Inventory Routes
  get 'inventory/search' => 'inventory#search'
  get 'inventory/search_books' => 'inventory#search_books'
  get 'inventory/search_books_city' => 'inventory#search_books_city'
  get 'inventory/autocomplete_author' => 'inventory#autocomplete_author'
  get 'inventory/autocomplete_book_name' => 'inventory#autocomplete_book_name'
  get 'inventory/autocomplete_book_details' => 'inventory#autocomplete_book_details'
  get 'inventory/check_inventory_duplication' => 'inventory#check_inventory_duplication'

  # Transaction Routes
  get 'transaction/user_id' => 'transaction#user_id'
  get 'transaction/history' => 'transaction#history'
  get 'transaction/details/:id' => 'transaction#details', as: 'transaction_details'
  patch 'transaction/update_request_status_accept' => 'transaction#update_request_status_accept'
  patch 'transaction/update_request_status_reject' => 'transaction#update_request_status_reject'
  patch 'transaction/update_request_status_cancel' => 'transaction#update_request_status_cancel'
  patch 'transaction/update_request_status_return' => 'transaction#update_request_status_return'
  patch 'transaction/update_request_status_receive_lender' => 'transaction#update_request_status_receive_lender'
  patch 'transaction/update_request_status_receive_borrower' => 'transaction#update_request_status_receive_borrower'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions' }
  resources :profile, :address, :book, :inventory, :transaction, :chat

end

app/views/admin/_admin_user_addresses_view.html.erb
<h4>Address Info</h4>
<table id='adminaddress' class='table table-striped table-bordered table-condensed'>
  <thead>
    <tr>
      <th>Address</th>
      <th>Pin</th>
    </tr>
  </thead>

  <tbody>
    <% if @user.addresses.empty? %>
      <tr>
        <td colspan='6'>User has not added any addresses as of now </td>
      </tr>
    <% else %>
      <% @user.addresses.each do |ua| %>
        <tr>
          <td><%= ua.address_line1 %></td>
          <td><%= ua.pin %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/_admin_user_credentials_view.html.erb
<h4> User Info </h4>
<table class='table table-striped table-bordered table-condensed'>
	<thead>
		<tr>
			<th>User Id</th>
			<th>Registered Email</th>
			<th>Priveleges</th>
		</tr>
	</thead>
	
	<tbody>
		<tr>
			<td><%= @user.id %></td>
			<td><%= @user.email %></td>
			<td><%= @user.checkrole %></td>
		</tr>
	</tbody>

</table>

app/views/admin/_admin_user_inventories_view.html.erb
<h4>Current Books</h4>

<table class='table table-striped table-bordered table-condensed'>
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Author</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
    <% if @user.inventories.empty? %>
      <tr>
        <td colspan='4'>User has not uploaded any books as of now </td>
      </tr>
    <% else %>
      <% @user.inventories.where(deleted: false).each do |inventory| %>
        <tr>
          <td><%= inventory.book.book_name %></td>
          <td><%= inventory.book.author %></td>
          <td><%= inventory.status %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/_admin_user_login_stats_view.html.erb
<h4>Login Info</h4>
<table id='adminloginstats' class='table table-striped table-bordered table-condensed'>
  <thead>
    <tr>
      <th>Sign In Count</th>
      <th>Current Sign In </th>
      <th>Last Sign In</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @user.sign_in_count.to_s(:long) unless @user.sign_in_count.blank? %></td>
      <td><%= @user.current_sign_in_at.to_s(:long) unless @user.current_sign_in_at.blank?  %></td>
      <td><%= @user.last_sign_in_at.to_s(:long) unless @user.last_sign_in_at.blank?  %></td>
    </tr>
  </tbody>
</table>

app/views/admin/_admin_user_profile_view.html.erb
<h4> Profile Info </h4>
<table class='table table-striped table-bordered table-condensed'>
	<thead>
		<tr>
			<th>Name</th>
			<th>Date Of Birth</th>
			<th>Gender</th>
			<th>Current Status</th>
			<th>Phone Number</th>
			<th>SMS Updates</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<% if @user.profile.nil? %>
				<td colspan='6'> This User has not yet built his profile </td>
			<% else %>
				<td><%= @user.welcome_name %></td>
				<td><%= @user.profile.DoB.to_formatted_s(:long) %></td>
				<td><%= @user.profile.gender %></td>
				<td id='user_current_status'><%= @user.current_status %></td>
				<td><%= @user.profile.user_phone_no %></td>
				<td><%= @user.profile.sms_updates %></td>
			<% end %>
		</tr>
	</tbody>

</table>

app/views/admin/index.html.erb
<%= title('Admin') %>

<h3> User List </h3><br/>
<table id='admin_view' class='table table-striped table-bordered table-condensed datatable'>
  <thead>
    <tr>
      <th>User Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Current Status</th>
      <th>Priveleges</th>
   </tr>
  </thead>
  <tbody>
    <%  @user.each do |u| %>
      <tr>
        <td><%= link_to "#{u.id}", admin_user_details_path(user_id: u.id) %></td>
        <td><%= u.profile.user_first_name + " " + u.profile.user_last_name unless u.profile.blank? %></td>
        <td><%= u.email %></td>
        <td><%= u.current_status %></td>
        <td><%= u.checkrole %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_tag do %>
        <th><%= text_field_tag('search_id', nil, placeholder: 'Id', class: 'form-control') %></th>
        <th><%= text_field_tag('search_name', nil, placeholder: 'Name', class: 'form-control') %></th>
        <th><%= text_field_tag('search_email', nil, placeholder: 'Email', class: 'form-control') %></th>
        <th><%= text_field_tag('search_current_status', nil, placeholder: 'Current Status', class: 'form-control') %></th>
        <th><%= text_field_tag('search_priveleges', nil, placeholder: 'Priveleges', class: 'form-control') %></th>
      <% end %>
    </tr>
  </tfoot>
</table>
</br></br>

app/views/admin/user_details.html.erb
<%= title('User Details') %>

<% if current_user.id !=  @user.id %>
	<% if @locked %>
		<%= tag 'input', type: 'button', id: 'unbar_user', :class => 'btn btn-danger' , 'data-uid' => @user.id, value: 'Un Bar User' %>
	<% else %>
		<%= tag 'input', type: 'button', id: 'bar_user', :class => 'btn btn-danger' , 'data-uid' => @user.id, value: 'Bar User' %>
	<% end %>
<% end %>

<%= link_to 'Back', admin_index_path, class: 'btn btn-default' %></br></br>

<%= link_to "Click here for User's Transaction History", user_transaction_history_path(@user.id) %></br></br>

<%= render 'admin_user_credentials_view' %>
<%= render 'admin_user_profile_view' %>
<%= render 'admin_user_addresses_view' %>
<%= render 'admin_user_inventories_view' %>
<%= render 'admin_user_login_stats_view' %>

<div id='bar_user_confirm' title='Accept Request'>
  <p> You are about to bar this User </p>
</div>

<div id='bar_user_success' title='User Account Barred'>
  <p> User Account Barred Successfully </p>
</div>

<div id='unbar_user_confirm' title='Accept Request'>
  <p> You are about to un-bar this User </p>
</div>

<div id='unbar_user_success' title='User Account UnBarred'>
  <p> User Account Un-Barred Successfully </p>
</div>

<div id='error_message_generic' title='Error'>
  <p>Oops. Something went wrong. Please try again later</p>
</div>

<%= link_to 'Back', admin_index_path, class:'btn btn-default' %>
</br></br>

app/views/admin/user_transaction_history.html.erb
<%= title('User History') %>

<h3><%= User.find(params[:id]).full_name %>'s Transaction History</h3>

<%= content_tag 'a', 'Filter By Date Range ->', id: :dates_filter_toggle %><br/><br/>
<div id='dates_filter_div' style='display:none;'>
  <div class='col-md-3'>
    <%= text_field_tag :min_req, nil, placeholder: 'Min Req Date (YYYY-MM-DD)', class: 'form-control' %>
  </div>
  <div class='col-md-3'>
    <%= text_field_tag :max_req, nil, placeholder: 'Max Req Date (YYYY-MM-DD)', class: 'form-control' %>
  </div>
</div>
<br/>

<% if !@t_history.empty? %>
  <table id='<%= params[:id] %>_transaction_history' class='table table-striped table-bordered table-condensed datatable'>
    <thead>
      <tr>
        <th>Id</th>
        <th>Book Name</th>
        <th>Lender/Borrower</th>
        <th>Rating</th>
        <th>Request Date </th>
      </tr>
    <thead>

    <tbody>
      <% @t_history.each do |th| %>
        <tr>
          <td><%= link_to th.id, transaction_details_path(th.id) %></td>

          <% th_book = th.inventory.book %>
          <td><%= link_to th_book.book_name, book_history_path(th_book.id) %></td>

          <% if th.lender_id == current_user.id %>
            <td>
              <%= link_to th.borrower.full_name, "/profile/public_rating/#{th.id}" %> &nbsp;
            </td>

            <td>
              <%= th.borrower_feedback %>
            </td>
          <% else %>
            <td>
              <%= link_to th.lender.full_name, "/profile/public_rating/#{th.id}" %> &nbsp;
            </td>
            <td>
              <%= th.lender_feedback %>
            </td>
          <% end %>

          <td><%= th.request_date.to_date.to_s %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <%= form_tag do %>
          <th><%= text_field_tag('search_id', nil, placeholder: 'Id', class: 'form-control') %></th>
          <th><%= text_field_tag('search_book_name', nil, placeholder: 'Book Name', class: 'form-control') %></th>
          <th><%= text_field_tag('search_lb', nil, placeholder: 'Lender/Borrower', class: 'form-control') %></th>
          <th><%= text_field_tag('search_rating', nil, placeholder: 'Rating', class: 'form-control') %></th>
          <th><%= text_field_tag('search_req_date', nil, placeholder: 'Req Date', class: 'form-control') %></th>
        <% end %>
      </tr>
    </tfoot>
  </table>
<% end %>