config/routes.rb
ProjectLectito::Application.routes.draw do

  # Devise routes
  authenticated :user do
    root :to => 'inventory#search'
  end

  unauthenticated :user do
    devise_scope :user do 
      get '/' => 'devise/sessions#new'
      get '/users/confirmation/new' => 'devise/passwords#new'
      get '/inventory/search' => 'devise/sessions#new'
    end
  end

  # Chat Routes
  get 'chat/box_chat_history' => 'chat#box_chat_history'
  post 'chat/new_chat' => 'chat#new_chat'

  # Profile Routes
  get 'profile/rating' => 'profile#rating'
  get 'profile/verification' => 'profile#otp'
  get 'profile/otp_resend' => 'profile#otp_resend'
  get 'profile/otp_verified' => 'profile#otp_verified'
  get 'profile/otp_verification' => 'profile#otp_verification'
  get 'profile/public_rating/:tr_id' => 'profile#public_rating'
  get 'profile/user_barred_signout' => 'profile#user_barred_signout'
  #FIXME - Patch gives FF Popup error
  post 'profile/online' => 'profile#online'

  # Address Routes
  get 'address/autocomplete_area' => 'address#autocomplete_area'
  get 'address/:id/autocomplete_area' => 'address#autocomplete_area'

  # Admin routes
  get 'admin' => 'admin#index', as: 'admin_index'
  get 'admin/user_details' => 'admin#user_details'
  get 'admin/user_transaction_history/:id' => 'admin#user_transaction_history', as: 'user_transaction_history'
  patch 'admin/bar_user' => 'admin#bar_user'
  patch 'admin/unbar_user' => 'admin#unbar_user'

  get 'devise/User'

  # Book Routes
  get 'book/history/:id' => 'book#history', as: 'book_history'
  get 'book/book_status' => 'book#book_status'
  get 'book/available_book_stats' => 'book#available_book_stats'
  get 'book/borrowed_book_stats' => 'book#borrowed_book_stats'

  # Inventory Routes
  get 'inventory/search' => 'inventory#search'
  get 'inventory/search_books' => 'inventory#search_books'
  get 'inventory/search_books_city' => 'inventory#search_books_city'
  get 'inventory/autocomplete_author' => 'inventory#autocomplete_author'
  get 'inventory/autocomplete_book_name' => 'inventory#autocomplete_book_name'
  get 'inventory/autocomplete_book_details' => 'inventory#autocomplete_book_details'
  get 'inventory/check_inventory_duplication' => 'inventory#check_inventory_duplication'

  # Transaction Routes
  get 'transaction/user_id' => 'transaction#user_id'
  get 'transaction/history' => 'transaction#history'
  get 'transaction/details/:id' => 'transaction#details', as: 'transaction_details'
  patch 'transaction/update_request_status_accept' => 'transaction#update_request_status_accept'
  patch 'transaction/update_request_status_reject' => 'transaction#update_request_status_reject'
  patch 'transaction/update_request_status_cancel' => 'transaction#update_request_status_cancel'
  patch 'transaction/update_request_status_return' => 'transaction#update_request_status_return'
  patch 'transaction/update_request_status_receive_lender' => 'transaction#update_request_status_receive_lender'
  patch 'transaction/update_request_status_receive_borrower' => 'transaction#update_request_status_receive_borrower'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions' }
  resources :profile, :address, :book, :inventory, :transaction, :chat

end

app/models/book.rb
# Model describing attributes of a Book
class Book < ActiveRecord::Base

  validates :isbn, :author, :book_name, :language, :genre, presence: { message: "Can't be empty" }

  # Associations

  has_many :inventories
  has_many :users, through: :inventories
  
end

app/controllers/book_controller.rb
# Controller for Book Model
class BookController < ApplicationController
  include ApplicationHelper
  before_action :otp_verified?
  
  load_and_authorize_resource class: Book

  def new
    @book = Book.new
    chatbox
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_index_path
      flash[:notice] = 'The Book has been added '
    else
      render 'new'
    end
  end

  def index
    @book = Book.all.page(params[:page]).per(10)
    chatbox
  end

  def edit
    @book = Book.find(params[:id])
    chatbox
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to book_index_path
    flash[:info] = 'The Book has been deleted '
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes(book_params)
    redirect_to book_index_path
    flash[:info] = 'The Book details have been updated '
  end

  def history
    @book = Book.find(params[:id])
    @b_history = []
    relevant_inventory = Inventory.where(book_id: @book.id)
    relevant_inventory.each do |ri|
      transaction_for_inventory = Transaction.where(inventory_id: ri.id, status: 'Complete')
      transaction_for_inventory.each do |tfi|
        @b_history.push(tfi)
      end
    end
    
    @b_history.sort_by! { |bh| bh.request_date }
    @b_history.reverse!
  end

  def book_status
    @available = Inventory.where(deleted: :false,
                                 status: 'Available',
                                 book_id: params[:book_id]).count

    @borrowed = Inventory.where(deleted: :false,
                                status: 'Unavailable',
                                book_id: params[:book_id]).count
  end

  def available_book_stats
    @available_list = Inventory.where(deleted: :false,
                                      status: 'Available',
                                      book_id: params[:book_id])
  end

  def borrowed_book_stats
    @borrowed_list = Inventory.where(deleted: :false,
                                     status: 'Unavailable',
                                     book_id: params[:book_id])
  end

  private

  def book_params
    params.require(:book).permit(:isbn, :author, :book_name, :genre, :language)
  end
end

app/helpers/book_helper.rb
# Book Helper
module BookHelper
end

app/views/book/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class='well'>
    <div id='error_explanation'>
      <div class='alert alert-error'>
        The form contains <%= pluralize(@book.errors.count, 'error') %>.
      </div>
      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/book/available_book_stats.js.erb
var $status_row ="<tbody>"
book_id = <%= params[:book_id] %>

available_tr = "#sub_available_list_" + book_id
borrowed_tr = "#sub_borrowed_list_" + book_id
sub_sub_table_id = "#book_count_status_" + book_id + " tr:last";

$(available_tr).remove();
$(borrowed_tr).remove();

$final_table ="<tr id='sub_available_list_" + book_id +"'><td colspan='2'><table id='sub_available_list_table' class='table table-hover table-condensed table-bordered'>"
$table_ending = "</tbody></table></td></tr>"
$table_header1 = "<tr id='sub_search_results_table_header1'><th>City</th><th>Rental</th></tr></thead>"
$table_header2 = "<thead><tr id='sub_search_results_table_header2'><th colspan='3'>Available</th></tr>"
<% if @available_list.empty? %>
	$status_row += "<tbody><tr><td colspan='2'>Sorry, No Copies of this Book have been borrowed currently</td></tr></tbody>"
<% else %>
	<%= i = 0 %>
	<% while i< @available_list.length %>
		$status_row += "<tr><td><%= Address.find(@available_list[i].available_in_city).city %></td><td><%= @available_list[i].rental_price.to_s %></td></tr>"
		<% i+= 1 %>	
	<% end %>
<% end %>

$final_table = $final_table + $table_header2 + $table_header1 + $status_row + $table_ending

$(sub_sub_table_id).after($final_table);

app/views/book/book_status.js.erb
var book_id, row_number;

book_id = <%= params[:book_id] %>
row_number = <%= params[:row_number] %>
$table = $("<table>")
sub_table_id = "sub_book_status_table_" + book_id
sub_table_id_s = "#" + sub_table_id
tr_id = "book_count_status_" + book_id

$(sub_table_id_s).remove()

$table_begining ="<tr id='" + tr_id + "'><td colspan='5'><table id='" + sub_table_id + "'class='table table-hover table-condensed table-bordered'>"
$table_ending = "</tbody></table></td></tr>"
$table_header = "<thead><tr id='sub_search_results_table_header'><th>Available</th><th>Borrowed</th></tr></thead>"
$status_row = "<tbody><tr data-specific_stats='closed'><td id='available_" + book_id + "'><%= @available %></td><td id='borrowed_" + book_id + "'><%= @borrowed %></tr></tbody>"
$final_table = $table_begining + $table_header + $status_row + $table_ending

$("#bookdetail_table > tbody > tr").eq(row_number).after($final_table);

app/views/book/borrowed_book_stats.js.erb
var $status_row ="<tbody>"
book_id = <%= params[:book_id] %>

available_tr = "#sub_available_list_" + book_id
borrowed_tr = "#sub_borrowed_list_" + book_id
sub_sub_table_id = "#book_count_status_" + book_id + " tr:last";

$(available_tr).remove();
$(borrowed_tr).remove();

$final_table ="<tr id='sub_borrowed_list_" + book_id +"'><td colspan='2'><table id='sub_borrowed_list_table' class='table table-hover table-condensed table-bordered'>"
$table_ending = "</tbody></table></td></tr>"
$table_header1 = "<tr id='sub_search_results_table_header1'><th>City</th><th>Rental</th></tr></thead>"
$table_header2 = "<thead><tr id='sub_search_results_table_header2'><th colspan='3'>Borrowed</th></tr>"
<% if @borrowed_list.empty? %>
	$status_row += "<tbody><tr><td colspan='2'>Sorry, No Copies of this Book have been borrowed currently</td></tr></tbody>"
<% else %>
	<%= i = 0 %>
	<% while i< @borrowed_list.length %>
		$status_row += "<tbody><tr><td><%= Address.find(@borrowed_list[i].available_in_city).city %></td><td><%= @borrowed_list[i].rental_price.to_s %></td></tr>"
		<% i+= 1 %>
	<% end %>
<% end %>

$final_table = $final_table + $table_header2 + $table_header1 + $status_row + $table_ending

$(sub_sub_table_id).after($final_table);

app/views/book/edit.html.erb
<%= title('Edit Book') %>

<h3>Edit <%= @book.book_name %> Details</h3></br>

<div class='col-md-3'>

  <div class='form_padding'>

    <%= form_for @book, url: book_path do |f| %>

      <%= render 'error_messages' %>

      <%= f.text_field :isbn, placeholder: :ISBN, required: :true, class: 'form-control' %>

      <%= f.text_field :book_name, placeholder: 'Book Name', required: :true, class: 'form-control' %>

      <%= f.text_field :author, placeholder: :Author, required: :true, class: 'form-control' %>
      	
      <%= f.text_field :language, placeholder: :Language, required: :true, class: 'form-control' %>

      <%= f.text_field :genre, placeholder: :Genre, required: :true, class: 'form-control' %>

      </br>

      <%= f.submit 'Update', class: 'btn btn-default' %>
      <%= link_to 'Back', book_index_path, class: 'btn btn-default' %>

    <% end %>

  </div>

</div>

app/views/book/history.html.erb
<%= title('Book History') %>

<div class='row'>

  <h3><%= @book.book_name %> History</h3><br/>
  <div class='col-md-12 well'>
    <ul style='list-style-type: none'>
      <div class='col-md-2'>
        <li>ISBN</li>
        <li>Genre</li>
      </div>
      <div class='col-md-2'>
        <li>: <%= @book.isbn %></li>
        <li>: <%= @book.genre %></li>
      </div>
      <div class='col-md-2'>
        <li>Author</li>
        <li>Language</li>
      </div>
      <div class='col-md-2'>
        <li>: <%= @book.author %></li>
        <li>: <%= @book.language %></li>
      </div>
      <div>
        <div class='col-md-2'>
      </div>
    </ul>
  </div>
  
  <table id='<%= @book.id %>_book_history' class='table table-striped table-bordered table-hover table-condensed datatable'>
    <thead>
      <tr>
        <th>Id</th>
        <th>Lender</th>
        <th>Borrower</th>
        <th>Request Date</th>
        <th>Borrow Duration</th>
        <th>Total Duration</th>
      </tr>
    </thead>
    <tbody>
      <% @b_history.each do |bh| %>
        <tr>
          <td><%= link_to bh.id, transaction_details_path(bh.id) %></td>
          <td><%= link_to bh.lender.full_name, "/profile/public_rating/#{bh.id}" %></td>
          <td><%= link_to bh.borrower.full_name, "/profile/public_rating/#{bh.id}" %></td>
          <td><%= bh.request_date.to_s(:long) %></td>
          <td><%= ((bh.returned_date - bh.received_date)/60/60/24).ceil %></td>
          <td><%= ((bh.return_received_date - bh.request_date)/60/60/24).ceil %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <%= form_tag do %>
          <th><%= text_field_tag('search_id', nil, placeholder: 'Id', class: 'form-control') %></th>
          <th><%= text_field_tag('search_lender', nil, placeholder: 'Lender', class: 'form-control') %></th>
          <th><%= text_field_tag('search_borrower', nil, placeholder: 'Borrower', class: 'form-control') %></th>
          <th><%= text_field_tag('search_req_date', nil, placeholder: 'Request Date', class: 'form-control') %></th>
          <th><%= text_field_tag('search_b_duration', nil, placeholder: 'Borrowed', class: 'form-control') %></th>
          <th><%= text_field_tag('search_t_duration', nil, placeholder: 'Total', class: 'form-control') %></th>
        <% end %>
      </tr>
    </tfoot>
  </table>
  <br/>
</div>

app/views/book/index.html.erb
<%= title('Books') %>

<h3>Current Books</h3><br/>

<%= link_to 'Add a Book', new_book_path, class: 'btn btn-default' %><br/><br/>

<%= paginate @book %>

<table class='table table-striped table-bordered table-hover table-condensed' id='bookdetail_table'>
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Author</th>
      <th colspan= '3'>Copies (T, A, B)</th>
      <th colspan='2'>Manage</th>
    </tr>
  </thead>
  <tbody>
    <% @book.each do |book| %>
      <tr id=<%= book.id %> data-general_stats='closed'>
        <td><%= link_to book.book_name, book_history_path(book.id) %></td>
        <td><%= book.author %></td>
        <td><%= Inventory.where(book_id: book.id).count %></td>
        <td><%= Inventory.where(book_id: book.id, status: 'Available').count %></td>
        <td><%= Inventory.where(book_id: book.id).where.not(status: 'Available').count %></td>
        <td class='manage'><%= link_to 'Edit', edit_book_path(book.id), class: 'btn btn-default' %></td>
        <td class='manage'><%= link_to 'Delete', book_path(book.id), method: 'delete', data: { confirm: 'Are You Sure' }, class: 'btn btn-default', disabled: :true %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

app/views/book/new.html.erb
<%= title('New Book') %>

<h3>Add a book</h3></br>

<div class='col-md-3'>

  <div class='form_padding'>

    <%= form_for @book, url: book_index_path do |f| %>

      <%= render 'error_messages' %>

      <%= f.text_field :isbn, placeholder: :ISBN, required: :true, class: 'form-control' %>

      <%= f.text_field :book_name, placeholder: 'Book Name', required: :true, class: 'form-control' %>

      <%= f.text_field :author, placeholder: :Author, required: :true, class: 'form-control' %>

      <%= f.text_field :language, placeholder: :Language, required: :true, class: 'form-control' %>

      <%= f.text_field :genre, placeholder: :Genre, required: :true, class: 'form-control' %>

      </br>

      <%= f.submit 'Add', class: 'btn btn-default' %>
      <%= link_to 'Back', book_index_path, class: 'btn btn-default' %>

    <% end %>

  </div>

</div>