config/routes.rb
ProjectLectito::Application.routes.draw do

  # Devise routes
  authenticated :user do
    root :to => 'inventory#search'
  end

  unauthenticated :user do
    devise_scope :user do 
      get '/' => 'devise/sessions#new'
      get '/users/confirmation/new' => 'devise/passwords#new'
      get '/inventory/search' => 'devise/sessions#new'
    end
  end

  # Chat Routes
  get 'chat/box_chat_history' => 'chat#box_chat_history'
  post 'chat/new_chat' => 'chat#new_chat'

  # Profile Routes
  get 'profile/rating' => 'profile#rating'
  get 'profile/verification' => 'profile#otp'
  get 'profile/otp_resend' => 'profile#otp_resend'
  get 'profile/otp_verified' => 'profile#otp_verified'
  get 'profile/otp_verification' => 'profile#otp_verification'
  get 'profile/public_rating/:tr_id' => 'profile#public_rating'
  get 'profile/user_barred_signout' => 'profile#user_barred_signout'
  #FIXME - Patch gives FF Popup error
  post 'profile/online' => 'profile#online'

  # Address Routes
  get 'address/autocomplete_area' => 'address#autocomplete_area'
  get 'address/:id/autocomplete_area' => 'address#autocomplete_area'

  # Admin routes
  get 'admin' => 'admin#index', as: 'admin_index'
  get 'admin/user_details' => 'admin#user_details'
  get 'admin/user_transaction_history/:id' => 'admin#user_transaction_history', as: 'user_transaction_history'
  patch 'admin/bar_user' => 'admin#bar_user'
  patch 'admin/unbar_user' => 'admin#unbar_user'

  get 'devise/User'

  # Book Routes
  get 'book/history/:id' => 'book#history', as: 'book_history'
  get 'book/book_status' => 'book#book_status'
  get 'book/available_book_stats' => 'book#available_book_stats'
  get 'book/borrowed_book_stats' => 'book#borrowed_book_stats'

  # Inventory Routes
  get 'inventory/search' => 'inventory#search'
  get 'inventory/search_books' => 'inventory#search_books'
  get 'inventory/search_books_city' => 'inventory#search_books_city'
  get 'inventory/autocomplete_author' => 'inventory#autocomplete_author'
  get 'inventory/autocomplete_book_name' => 'inventory#autocomplete_book_name'
  get 'inventory/autocomplete_book_details' => 'inventory#autocomplete_book_details'
  get 'inventory/check_inventory_duplication' => 'inventory#check_inventory_duplication'

  # Transaction Routes
  get 'transaction/user_id' => 'transaction#user_id'
  get 'transaction/history' => 'transaction#history'
  get 'transaction/details/:id' => 'transaction#details', as: 'transaction_details'
  patch 'transaction/update_request_status_accept' => 'transaction#update_request_status_accept'
  patch 'transaction/update_request_status_reject' => 'transaction#update_request_status_reject'
  patch 'transaction/update_request_status_cancel' => 'transaction#update_request_status_cancel'
  patch 'transaction/update_request_status_return' => 'transaction#update_request_status_return'
  patch 'transaction/update_request_status_receive_lender' => 'transaction#update_request_status_receive_lender'
  patch 'transaction/update_request_status_receive_borrower' => 'transaction#update_request_status_receive_borrower'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions' }
  resources :profile, :address, :book, :inventory, :transaction, :chat

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base

  validates :available_in_city, :status, presence: true

  # Associations
  has_many :transactions
  belongs_to :book
  belongs_to :user
  belongs_to :address, foreign_key: :available_in_city
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
	include ApplicationHelper
	#before_action :require_profile, :require_address
	if :authenticate_user!
		before_action :require_profile
		before_action :otp_verified?
		before_action :require_address
	end

	def index
		@inventory = current_user.inventories.where(deleted: :false).page(params[:page]).per(8)
		chatbox
	end

	def new
		@book = Book.new
		@address = current_user.addresses
		chatbox
	end

	def create
	#TODO - Send New book params in a form so strong params can be updated
		if params[:book_id] == '0'
			new_book = Book.new
			new_book.book_name = params[:book_name]
			new_book.isbn = params[:isbn]
			new_book.author = params[:author]
			new_book.language = params[:language]
			new_book.genre = params[:genre]

			if new_book.save!
				@inventory = Inventory.new(inventory_params)
				@inventory.user_id = current_user.id
				@inventory.book_id = new_book.id
				@inventory.status = params[:status]
				@inventory.no_of_borrows = 0
				if @inventory.save!
					redirect_to inventory_index_path
					flash[:notice] = 'The book has been added to your inventory'
				else
					render 'new'
				end
			end
		else
			@inventory = Inventory.new
			@inventory.user_id = current_user.id
			@inventory.book_id = params[:book_id]
			@inventory.available_in_city = params[:inventory][:available_in_city]
			@inventory.status = params[:status]
			@inventory.no_of_borrows = 0
	 		if @inventory.save!
				redirect_to inventory_index_path
				flash[:notice] = 'The book has been added to your inventory'
			else
				render 'new'
			end
		end
		
		chatbox
	end

	def edit
		@inventory = Inventory.where(id: params[:id]).take
		@address = current_user.addresses
		chatbox
	end

	def update
		#FIXME Update_attributes needs to be done individually :S
		@inventory = Inventory.where(id: params[:id]).take
   		@inventory.update_attributes(inventory_params)
   		@inventory.status = params[:status]
   		
   		if @inventory.save!
    		redirect_to inventory_index_path
    		flash[:notice] = 'The inventory has been updated'
    	end
	end

	def destroy
		@inventory = Inventory.where(id: params[:id]).take
		@inventory.deleted = true
		@inventory.status = 'Deleted'
		if @inventory.save!
			redirect_to inventory_index_path
			flash[:notice] = 'The book has been deleted from your inventory'
		end
	end

	def search_books
		if params[:search_by_book_name] == ''
			@books = Book.where('author LIKE ?', "%#{params[:search_by_author]}%")
		elsif params[:search_by_author] == ''
			@books = Book.where('book_name LIKE ?', "%#{params[:search_by_book_name]}%")
		else
			@books = Book.where('book_name LIKE ? AND author LIKE ? ', "%#{params[:search_by_book_name]}%", "%#{params[:search_by_author]}%")
		end

		@book_array = []

		@books.each do |book|
			if user_signed_in?
				@users_with_book = Inventory.where('book_id = ? AND user_id != ? AND status = ? AND deleted = ?', book, current_user.id, "Available", false).take
			else
				@users_with_book = Inventory.where('book_id = ? AND status = ? AND deleted = ?', book, "Available", false).take
			end

			if !@users_with_book.nil?

				# Of all Users who have the book, check who all are in the city as selected by user
				# Merge this list with the address of each user who meets the criteria.
				
				@address_uwb_in_city = @users_with_book.user.addresses.where(id: @users_with_book.available_in_city).take
				@delivery_uwb = @users_with_book.user.is_delivery

				if user_signed_in?
					if (@address_uwb_in_city.city == params[:city])
						@book_array << book
					end
					# if current_user.is_delivery
			 	# 		if ((@address_uwb_in_city.city == params[:city]) and (current_user.is_delivery == @delivery_uwb))
					# 		@book_array << book
					# 	end
					# else
					# 	@book_array << book
					# end
				else
					if @address_uwb_in_city.city == params[:city]
						@book_array << book
					end
				end
			end
		end

		respond_to do |format|
  		format.js
		end
	end

	def search_books_city

		@users_with_book_in_city = []
		@addresses_with_book_in_city = []
		@users_and_address = []
		@transactions_requested = []

		# Find all users apart from self, who have the book
	 	if user_signed_in?
			@users_with_book = Inventory.where('book_id = ? AND user_id != ? AND status = ? AND deleted = ?', params[:book_id], current_user.id, 'Available', false)
			# Of all Users who have the book, check who all are in the city as selected by user
			# Merge this list with the address of each user who meets the criteria.
			@users_with_book.each do |u_wb|
				#address of user who has the book
				@address_uwb_in_city = u_wb.user.addresses.where(id: u_wb.available_in_city).take

				#TODO make the if more efficient
				if @address_uwb_in_city.city == params[:city]
					@users_and_address << u_wb.clone
					@users_and_address << @address_uwb_in_city
					@transactions_requested << Transaction.where(borrower_id: current_user.id, status: 'Pending', inventory_id: u_wb.id).pluck(:inventory_id)
				end
			end
		else
			@users_with_book = Inventory.where('book_id = ? AND status = ? AND deleted = ?', params[:book_id], 'Available', false)
			# Of all Users who have the book, check who all are in the city as selected by user
			# Merge this list with the address of each user who meets the criteria.
			@users_with_book.each do |u_wb|
				#address of user who has the book
				@address_uwb_in_city = u_wb.user.addresses.where(id: u_wb.available_in_city).take

				#TODO make the if more efficient
				if @address_uwb_in_city.city == params[:city]
					@users_and_address << u_wb.clone
					@users_and_address << @address_uwb_in_city
					@transactions_requested << Transaction.where(status: 'Pending', inventory_id: u_wb.id).pluck(:inventory_id)
				end
			end
		end

		@transactions_requested = @transactions_requested.flatten
		@transactions_requested = @transactions_requested.map(&:inspect).join(', ')

		respond_to do |format|
  		format.js
  	end
	end

	def search
		if user_signed_in?
			@borrow = Transaction.where(borrower_id: current_user.id, status: 'Pending').last(5)
			@lend = Transaction.where(lender_id: current_user.id, status: 'Pending')
			@accept = Transaction.where('lender_id = ? AND ( status = ? OR status = ? OR status = ?)', current_user.id, 'Accepted', 'Returned', 'Received Borrower' )
			@current = Transaction.where('borrower_id = ? AND ( status = ? OR status = ?)', current_user.id, 'Accepted', 'Received Borrower' )
			@received = Transaction.where(lender_id: current_user.id, status: 'Returned')

			chatbox
		else
			@borrow = nil
			@lend = nil
			@accept = nil
			@current = nil
			@received = nil
		end
	end

	def autocomplete_author
		if params[:book_name].nil?
			@authors_books = Book.where('lower(author) like ? ', "%#{params[:author].downcase}%").pluck(:author).uniq
		else
			@authors_books = Book.where('lower(author) like ? AND lower(book_name) like ?', "%#{params[:author].downcase}%", "%#{params[:book_name]}%").pluck(:author).uniq
		end

		respond_to do |format|
  		format.json { render json: @authors_books.to_json }
  	end
	end

	def autocomplete_book_name
		@book_name_books = Book.where('lower(author) like ? AND lower(book_name) like ?', "%#{params[:author].downcase}%", "%#{params[:book_name].downcase}%").pluck(:book_name)

		respond_to do |format|
  		format.json { render json: @book_name_books.to_json }
  	end
	end

	def autocomplete_book_details
		@books = Book.where('lower(book_name) like ?', "%#{params[:book_name].downcase}%")

		respond_to do |format|
  		format.json { render json: @books.to_json }
  	end
	end

	private

	def inventory_params
		params.require(:inventory).permit(:available_in_city)
	end

	def require_profile
		if user_signed_in?
    	if current_user.profile.nil?
    		flash[:notice] = 'Please complete your profile'
    		redirect_to new_profile_path
    	else
    		return false
    	end
  	end
  end	

	def require_address
		if user_signed_in?
			if !current_user.profile.nil? && current_user.otp_verification
	    	if current_user.addresses.empty?
	    		flash[:notice] = 'Please Enter at least one Address'
	    		redirect_to new_address_path
	    	else
	    		return false
	    	end
	    end
    end
	end	
end

app/helpers/inventory_helper.rb
# Inventory Helper
module InventoryHelper
  def india_cities
    [
      ['Pune', 'Pune']
    ]
  end

  def search_options
  [
    ['Author', 'author'],
    ['Book Name', 'book_name']
  ]
  end
end

app/views/inventory/_dialogs.html.erb
<div id='accept_request_confirm' title='Accept Request'>
  <p id='accept_info'></p>
  <p id='user_dispatch_date'>Please specify a good time to pick up the book for delivery </p>
  <div id='accept_datepicker'>
    <%= text_field_tag :dispatch_date, Date.tomorrow, placeholder: 'Select Date' %></br>
  </div>
  <input type='radio' name='dispatchTime' value='Before 1 PM' checked='true'> Before 1 PM <br>
  <input type='radio' name='dispatchTime' value='After 1 PM'>  After 1 PM
</div>

<div id='return_request_confirm' title='Return Request'>
  <p id='return_info'></p>
  <p id='return_dispatch_date'>Please specify a good time to pick up the book for delivery </p>
  <div id='return_info_datepicker'>
    <%= text_field_tag :return_pickup_date, Date.tomorrow, placeholder: 'Select Date' %></br>
  </div>
  <input type='radio' name='return_time' value='Before 1 PM' checked='true'> Before 1 PM <br>
  <input type='radio' name='return_time' value='After 1 PM'>  After 1 PM
</div>

<div id='lender_received_book_confirm' title='Return Request'>
  <p>Please rate your experience to complete this transaction </p>
  <input type='radio' name='lender_feedback' value='good' checked='true'> Good <br/>
  <input type='radio' name='lender_feedback' value='neutral'>  Neutral <br/>
  <input type='radio' name='lender_feedback' value='bad'>  Bad <br/><br/>
  <div id='lender_comments_div'>
    <%= text_area_tag :lender_comments, nil, placeholder: :Comments, class: :feedback_textarea %></br>
  </div>
</div>

<div id='borrower_returned_book_confirm' title='Return Request'>
  <p>Please rate your experience to complete this transaction </p>
  <input type='radio' name='borrower_feedback' value='good' checked='true'> Good <br/>
  <input type='radio' name='borrower_feedback' value='neutral'>  Neutral <br/>
  <input type='radio' name='borrower_feedback' value='bad'>  Bad <br/><br/>
  <div id='lender_comments_div'>
    <%= text_area_tag :borrower_comments, nil, placeholder: :Comments, class: 'feedback_textarea' %></br>
  </div>
</div>

<div id='error_message_generic' title='Error'>
  Oops. Something went wrong. Please try again later
</div>

<div id='error_message_403' title='Error'>
  You are not authorized to perform this action
</div>

<div id='borrow_confirm' title='Borrow Request'>
  <p>You are about to send a request to borrow - </p>
  <div id='borrow_confirm_title'></div>
  <div id='selftodel'></div>
</div>

<div id='reject_request_confirm' title='Reject Request'>
  <p>You are about to Reject this request</p>
  <input type='radio' name='rejectReason' value='Unavailable' checked='true'> I am currently Unavailable <br>
  <input type='radio' name='rejectReason' value='Do Not Wish To Lend'> I do not wish to lend this book as of now
</div>

<div id='cancel_transaction' title='Cancel Transaction'>
  Are you sure you want to cancel this request?
</div>

<div id='received_borrower_confirm' title='Received Book'>
  Have you received the book?
</div>

<div id='accept_self_confirm' title='Accept Request'>
  You are about to accept a request to lend out this book
</div>

<div id='handed_over_confirm' title='Book Handed Over'>
  Have you handed the book over ?
</div>

<div id='display_public_profile' title=''>
  <p id='total_books'>Total Books : <b></b></p>
  <p id='total_transactions'>Total Transactions : <b></b></p>
  <p id='good_transactions'>Good : <b></b></p>
  <p id='neutral_transactions'>Neutral : <b></b></p>
  <p id='bad_transactions'>Bad : <b></b></p>
  <p id='full_profile'>View Complete Profile<b></b></p>
</div>

app/views/inventory/edit.html.erb
<%= title('Edit My Book') %>

<h3>Edit book</h3><br/>

		<div class='col-md-4'>

			<div class='form_padding'>

				<%= form_tag  "/inventory/#{@inventory.id}", method: :put do %>

					<div id='edit_inventory'>

						<%= text_field_tag :book_name, Book.where(id: @inventory.book_id).take.book_name, placeholder: 'Book Name', required: true, width: '10', disabled: true, class: 'edit_inventory form-control'  %>

						<%= collection_select :inventory, :available_in_city, @address, :id, :address_summary, {}, { class: 'edit_inventory form-control' } %>

						<%= select_tag :status, options_for_select(['Available','Unavailable'], @inventory.status), placeholder: 'Current Status', class: 'edit_inventory form-control'  %>

					</div><br/>

					<%= submit_tag 'Update', class: 'btn btn-default' %>
					<%= link_to 'Back', inventory_index_path, class: 'btn btn-default' %>

				<% end %>
			</div>
		</div>

		<div class='form_padding'>
			<div class='col-md-4'>
				<ul style='list-style-type: none'>
					<li><%= text_field_tag :isbn, Book.where(id: @inventory.book_id).take.isbn, disabled: true, placeholder: :ISBN , class: 'edit_inventory form-control' %></li>
					<li><%= text_field_tag :author , Book.where(id: @inventory.book_id).take.author, disabled: true, placeholder: :Author , class: 'edit_inventory form-control' %></li>
					<li><%= text_field_tag :language, Book.where(id: @inventory.book_id).take.language, disabled: true, placeholder: :Language , class: 'edit_inventory form-control' %></li>
					<li><%= text_field_tag :genre, Book.where(id: @inventory.book_id).take.genre, disabled: true, placeholder: :Genre , class: 'edit_inventory form-control' %></li>
				</ul>
			</div>
		</div>

app/views/inventory/index.html.erb
<%= title('My Books') %>

<h3>My Books</h3>

<%= paginate @inventory %>

<table class='table table-striped table-bordered table-condensed'>
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Author</th>
      <th>Available @</th>
      <th>Current Status</th>
      <th colspan='2'>Manage</th>
    </tr>
  <thead>

  <tbody>
    <% if @inventory.blank? %>
      <tr>
        <td colspan='5' class='text-center'>These are the books I'd like to lend out...</td>
      </tr>
    <% else %>
      <% @inventory.each do |inventory| %>
        <tr>
          <td><%= inventory.book.book_name %></td>
          <td><%= inventory.book.author %></td>
          <td><%= inventory.user.addresses.find(inventory.available_in_city).address_summary %></td>
          <td><%= inventory.status %></td>
          <% if inventory.status == 'Rented Out' %>
            <td class='manage'><%= link_to 'Edit', edit_inventory_path(inventory.id), disabled: :true, class: 'btn btn-default '%></td>
            <td class='manage'><%= link_to 'Delete', inventory_path(inventory.id), disabled: :true, method: 'delete', class: 'btn btn-default ', data: { confirm: 'Are You sure?' } %></td>
          <% else %>
            <td class='manage'><%= link_to 'Edit', edit_inventory_path(inventory.id), class: 'btn btn-default '%></td>
            <td class='manage'><%= link_to 'Delete', inventory_path(inventory.id), method: 'delete', class: 'btn btn-default ', data: { confirm: 'Are You sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add a Book', new_inventory_path, class: 'btn btn-default' %><br/>

app/views/inventory/new.html.erb
<%= title('Add My Book') %>

<h3>Add a book</h3><br/>
	
	<div class='row'>
		<div class='col-md-12'>
			<div class='col-md-4'>
				<p hidden='true' id='book_name_empty'><i><b>No Such Book Found, Please enter the details</b></i></p>
				<div class='form_padding'>

					<%= form_tag inventory_index_path, id: 'add_book_form' do %>

						<div id='new_inventory'>
							<%= text_field_tag :book_name, nil, placeholder: 'Book Name', required: :true, width: '10', class: 'form-control' %>
							<%= collection_select :inventory, :available_in_city, @address, :id, :address_summary, {}, { class: 'form-control' } %>
							<%= select_tag :status, options_for_select(['Available','Unavailable'], 'Available'), placeholder: 'Current Status', class: 'form-control' %>
							</br>

							<div class='book_elements'>
								<%= hidden_field_tag :book_id %>
							</div>

						</div>
					
					</div>
				</div>

				<div class='col-md-4'>
					<div class='form_padding'>
						<%= text_field_tag :isbn, nil, disabled: true, placeholder: :ISBN, required: true, class: 'form-control new_book_element' %>
						<%= text_field_tag :author , nil, disabled: true, placeholder: :Author, required: true, class: 'form-control new_book_element' %>
						<%= text_field_tag :language, nil, disabled: true, placeholder: :Language, required: true, class: 'form-control new_book_element' %>
						<%= text_field_tag :genre, nil, disabled: true, placeholder: :Genre, required: true, class: 'form-control new_book_element' %>
					</div>
				</div>
			</div>
		</div>
	
		<div class='row'>
			<div class='col-md-12'>
				<div class='col-md-4'>
					<%= submit_tag 'Add Book', id: :add_book, class: 'btn btn-default', disabled: :true %>
					<%= link_to 'Back', inventory_index_path, class: 'btn btn-default' %>
				<% end %>
			</div>
		</div>
	</div>

app/views/inventory/search.html.erb
<%= title('Search') %>

<h3>Search</h3>

<% if @borrow.blank? %>
  <div id='borrow_requests_div' hidden='true'>
  	<%= render 'transaction/borrow_requests' %>
  </div>
<% else %>
  <div id='borrow_requests_div'>
    <%= render 'transaction/borrow_requests' %>
  </div>
<% end %>

<% if @lend.blank? %>
  <div id='lend_requests_div' hidden='true'>
  	<%= render 'transaction/lend_requests' %>
  </div>
<% else %>
  <div id='lend_requests_div'>
      <%= render 'transaction/lend_requests' %>
    </div>
<% end %>

<% if @accept.blank? %>
  <div id='accepted_requests_div' hidden='true'>
  	<%= render 'transaction/accepted_requests' %>
  </div>
<% else %>
  <div id='accepted_requests_div'>
    <%= render 'transaction/accepted_requests' %>
  </div>
<% end %>

<% if @current.blank? %>
  <div id='current_books_div' hidden='true'>
    <%= render 'transaction/current_books' %>
  </div>
<% else %>
  <div id='current_books_div'>
    <%= render 'transaction/current_books' %>
  </div>
<% end %>

<h5>Search for a book that you'd like to borrow in your city!</h5>

<div class='col-md-4'>

  <div class='form_padding'>

    <%= form_tag() do %>

      <div id='city_validation'></div>

      <%= select_tag :city, options_for_select(india_cities), prompt: 'I live in..', class: 'form-control' %>

      <div id='author_book_validation'></div>

      <p hidden='true' id='author_empty'><i><b>No Such Author Found</b></i></p>

      <%= text_field_tag :search_by_author, nil, placeholder: 'Search By Author', class: 'form-control' %>  

      <p hidden='true' id='book_name_empty'><i><b>No Such Book Found</b></i></p>

      <%= text_field_tag :search_by_book_name, nil, placeholder: 'Search By Book Name', class: 'form-control' %>    

    <% end %>

    <%= tag 'input', type: 'button', id: 'search_books', class: 'btn btn-default' , value: 'Search' %></br></br>

  </div>

</div>

<div class='col-md-11'>
  <div>
    <h5 id='book_count'></h5>
  </div>
  <div id='search_text'></div>
  <div id='dynamicTable'></div>
</div>  

<%= render 'dialogs' %>

app/views/inventory/search_books.js.erb
<% #TODO Check for tbody addition %>

var $table, $tbody, author_data, book_name_data, rental_data, table_row_id;

$table = $("<table style='table-layout:fixed;'>");
$table.attr('class', 'table table-hover table-bordered');
$table.attr('id', 'search_results_table');
$table.append('<thead>').children('thead').append('<tr />').children('tr').append('<th>Author</th><th>Book Name</th>');
$tbody = $table.append('<tbody />').children('tbody');

if (<%= @book_array.empty? %>) {
	rental_data = "<td colspan='2' class='text-center'> Sorry, this book/books by this author arent available in your city, or have been lent out </td>";
	table_row_id = '<tr>';
	$tbody.append(table_row_id).children('tr:last').append(rental_data);
} else {
	<% @book_array.each do |b| %>
		author_data = '<td id=author_<%= b.id %>><%= b.author %></td><td><%= b.book_name %></td>';
		table_row_id = '<tr id=<%= b.id %> data-status=closed>';
		$tbody.append(table_row_id).children('tr:last').append(author_data).append(book_name_data);
	<% end %>
}
	$table.fadeIn(500).appendTo('#dynamicTable');