config/routes.rb
ProjectLectito::Application.routes.draw do

  # Devise routes
  authenticated :user do
    root :to => 'inventory#search'
  end

  unauthenticated :user do
    devise_scope :user do 
      get '/' => 'devise/sessions#new'
      get '/users/confirmation/new' => 'devise/passwords#new'
      get '/inventory/search' => 'devise/sessions#new'
    end
  end

  # Chat Routes
  get 'chat/box_chat_history' => 'chat#box_chat_history'
  post 'chat/new_chat' => 'chat#new_chat'

  # Profile Routes
  get 'profile/rating' => 'profile#rating'
  get 'profile/verification' => 'profile#otp'
  get 'profile/otp_resend' => 'profile#otp_resend'
  get 'profile/otp_verified' => 'profile#otp_verified'
  get 'profile/otp_verification' => 'profile#otp_verification'
  get 'profile/public_rating/:tr_id' => 'profile#public_rating'
  get 'profile/user_barred_signout' => 'profile#user_barred_signout'
  #FIXME - Patch gives FF Popup error
  post 'profile/online' => 'profile#online'

  # Address Routes
  get 'address/autocomplete_area' => 'address#autocomplete_area'
  get 'address/:id/autocomplete_area' => 'address#autocomplete_area'

  # Admin routes
  get 'admin' => 'admin#index', as: 'admin_index'
  get 'admin/user_details' => 'admin#user_details'
  get 'admin/user_transaction_history/:id' => 'admin#user_transaction_history', as: 'user_transaction_history'
  patch 'admin/bar_user' => 'admin#bar_user'
  patch 'admin/unbar_user' => 'admin#unbar_user'

  get 'devise/User'

  # Book Routes
  get 'book/history/:id' => 'book#history', as: 'book_history'
  get 'book/book_status' => 'book#book_status'
  get 'book/available_book_stats' => 'book#available_book_stats'
  get 'book/borrowed_book_stats' => 'book#borrowed_book_stats'

  # Inventory Routes
  get 'inventory/search' => 'inventory#search'
  get 'inventory/search_books' => 'inventory#search_books'
  get 'inventory/search_books_city' => 'inventory#search_books_city'
  get 'inventory/autocomplete_author' => 'inventory#autocomplete_author'
  get 'inventory/autocomplete_book_name' => 'inventory#autocomplete_book_name'
  get 'inventory/autocomplete_book_details' => 'inventory#autocomplete_book_details'
  get 'inventory/check_inventory_duplication' => 'inventory#check_inventory_duplication'

  # Transaction Routes
  get 'transaction/user_id' => 'transaction#user_id'
  get 'transaction/history' => 'transaction#history'
  get 'transaction/details/:id' => 'transaction#details', as: 'transaction_details'
  patch 'transaction/update_request_status_accept' => 'transaction#update_request_status_accept'
  patch 'transaction/update_request_status_reject' => 'transaction#update_request_status_reject'
  patch 'transaction/update_request_status_cancel' => 'transaction#update_request_status_cancel'
  patch 'transaction/update_request_status_return' => 'transaction#update_request_status_return'
  patch 'transaction/update_request_status_receive_lender' => 'transaction#update_request_status_receive_lender'
  patch 'transaction/update_request_status_receive_borrower' => 'transaction#update_request_status_receive_borrower'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions' }
  resources :profile, :address, :book, :inventory, :transaction, :chat

end

app/views/layouts/_footer.html.erb
<footer>
  <div class='row'>
    <div class='col-md-10 col-md-offset-1'>
      <hr/>
        <ul style='font-size:12px;'>
        <div class='col-md-2 footer_padding'>
          <li>&copy; ProjectLectito 2014</li>
        </div>
        <div class='col-md-2 footer_padding'>
          <li >Terms of Service</li>
        </div>
        <div class='col-md-2 footer_padding'>
          <li>Privacy Policy</li>
        </div>
        <div class='col-md-2 footer_padding'>
          <li>Contact Us</li>
        </div>
        <div class='col-md-2 footer_padding'>
          <li>About Us</li>
        </div>
        <div class='col-md-2 '>
          <li>
            <i class='fa fa-facebook fa-2x'></i>
            <i class='fa fa-twitter fa-2x'></i>
            <i class='fa fa-google-plus fa-2x'></i>
          </li>
        </div>
      </ul>
      <hr/><hr/>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
  <div class='col-md-10 col-md-offset-1'>
    <% if user_signed_in? %>
      <div class='col-md-4'>
        <div class='navbar-header'>
           <a class='navbar-brand' href='/inventory/search'>Project Lectito</a>
        </div>
      </div>

      <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
        <div class='col-md-4'>
          <ul class='nav navbar-nav'>
            <li class="<%= 'active' if params[:controller] == 'inventory' && params[:action] == 'search' %>"><%= link_to ' Search ', inventory_search_path, id: :home_link %></li>
            <li class="dropdown <%= 'active' if params[:controller] == 'profile' || params[:controller] == 'address' || params[:controller] == 'transaction' %>">
              <a href='#' data-toggle='dropdown' class='dropdown-toggle header_hover'>Profile <b class='caret'></b></a>
              <ul class='dropdown-menu header_hover_sub'>
                <% if !current_user.profile.nil? %>
                  <li><%= link_to 'Personal', edit_profile_path(current_user.profile.id) %></li>
                <% end %> 
                <li><%= link_to 'Addresses', address_index_path  %></li>
                <li><%= link_to 'Rating', profile_rating_path  %></li>
                <li><%= link_to 'History', transaction_history_path %></li>
              </ul>
            </li>

            <li class="dropdown <%= 'active' if params[:controller] == 'chat' || ( params[:controller] == 'inventory' && params[:action] != 'search') %>">
              <a href='#' class='dropdown-toggle header_hover' data-toggle='dropdown'>Books <b class='caret'></b></a>
              <ul class='dropdown-menu header_hover_sub'>
                <li><%= link_to 'My Books', inventory_index_path %></li>
                <li><%= link_to 'Conversations', chat_index_path %></li>
              </ul>
            </li>

            <% if current_user.has_role? :admin %>
              <li class="dropdown <%= 'active' if params[:controller] == 'admin' || params[:controller] == 'book' %>">
                <a data-toggle='dropdown' class='dropdown-toggle header_hover' href='#'>Admin <b class='caret'></b></a>
                <ul class='dropdown-menu header_hover_sub'>
                  <li><%= link_to 'Users', admin_index_path %></li>
                  <li><%= link_to 'Books', book_index_path %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>

        <div class='col-md-4'>
          <ul class='nav navbar-right navbar-nav'>
            <li class='dropdown'>
              <a href='#' data-toggle='dropdown' class='dropdown-toggle header_hover'><%= current_user.welcome_name %> <b class='caret'></b></a>
              <ul class='dropdown-menu header_hover_sub'>
                <li><%= link_to 'Sign Out' ,destroy_user_session_path, method: :delete %></li>
                <li><%= link_to 'Change Password', edit_user_registration_path %></li>
              </ul>
            </li>
          </ul>
        </ul>
      </div>
    <% else %>
      <a href='#' class='navbar-brand'>ProjectLectito</a>
        <%= tag 'input', type: 'button', id: 'sign_in', class: 'btn btn-default btn-primary navbar-btn pull-right modal_login', value: 'Sign In' %></br></br>
    <% end %>
  </div>
</nav>

app/views/layouts/_sign_in.html.erb
<div id='sign_in_div'>
  <div class='row'>
    <div class='col-md-12'>
      <div class='col-md-7'>
        <div class='col-md-8'>
          <div class='form_padding'>
            <h5>Sign In</h5>
            <%= form_for(resource, as: resource_name, url: session_path(resource_name, class: 'form_elements_padding')) do |f| %>
                <%= f.email_field :email, autofocus: true, placeholder: :Email, class: 'form-control' %>
                <%= f.password_field :password, placeholder: "Password", class: 'form-control' %>
              <%= f.submit "Sign In", class: 'nfp btn btn-primary btn-sm', style:'margin:0px;' %><br/>
              <%= link_to "Forgot password", new_password_path(resource_name), class: :fplink %><br />
            <% end %>
          </div>
        </div>
        <div class='col-md-4 text-center'>
          <br/><br/><br/><br/>| OR |
        </div>
      </div>
      <div class='col-md-5 text-center'>
        <h5>Sign In Using</h5>
        <div class='sml'>
          <%= link_to image_tag('facebook.png', size: '64x64'), user_omniauth_authorize_path(:facebook) %>
          <%= link_to image_tag('twitter.png', size: '64x64'), user_omniauth_authorize_path(:twitter) %>
          <%= link_to image_tag('google+.png', size: '64x64'), user_omniauth_authorize_path(:google_oauth2) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!-- Responeible for responsive-ness on mobile devices -->
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class='wrapper'>
      <%= render 'layouts/header' %>
      <div class = 'container'>
        <div class = 'col-md-12 col-md-offset1'>
          <% if flash[:notice] %>
            <p class='label label-success'><%= flash[:notice] %></p><br/>
          <% end %>
          <% if flash[:error] %>
            <p class='label label-important'><%= flash[:error] %><br/></p>
          <% end %>
          <% if flash[:info] %> 
            <p class='label label-info'><%= flash[:info] %><br/></p>
          <% end %>
          <% if alert %>
            <p class='label label-danger'><%= alert %><br/></p>
          <% end %>
          <%= yield %>
          <% if user_signed_in? %>
            <div id='chat_divs'>
            </div>
          <% end %>
        </div>
      </div>
      <div class='push'></div>
      <% unless user_signed_in? %>
        <%= render 'layouts/sign_in' %>
      <% end %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>